# Default values for nginx-ingress

controller:
  enabled: true
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
    port:
      http: 80
      https: 443
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  admissionWebhooks:
    enabled: true
  extraArgs:
    controller-class: k8s.io/ingress-nginx
