# Default values for nginx-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Service configuration
service:
  type: NodePort
  port: 80

# Enable the ingress-nginx controller
controller:
  enabled: true
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

# Enable default backend
defaultBackend:
  enabled: true