apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-page
  labels:
    app: hello-page
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hello-page
  template:
    metadata:
      labels:
        app: hello-page
    spec:
      containers:
      - name: hello-page
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: hello-page-html