apiVersion: v1
kind: Service
metadata:
  name: hello-world-3
  labels:
    app: hello-world-3
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hello-world-3